/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  11155111: {
    API3OracleAdapter: {
      address: "0x111ef8C8d0d9875194B3D630319327620C5c9996",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_proxy",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "latestRoundData",
          outputs: [
            {
              internalType: "uint80",
              name: "",
              type: "uint80",
            },
            {
              internalType: "int256",
              name: "",
              type: "int256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint80",
              name: "",
              type: "uint80",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "proxy",
          outputs: [
            {
              internalType: "contract IApi3Proxy",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 11633917,
    },
    AegisV3: {
      address: "0xA514727e7EC43F6a99ceB11F25df36c922e040Ad",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
          ],
          name: "AddressEmptyCode",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "AddressInsufficientBalance",
          type: "error",
        },
        {
          inputs: [],
          name: "FailedInnerCall",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "SafeERC20FailedOperation",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "batchId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "asset",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "openEnd",
              type: "uint256",
            },
          ],
          name: "BatchCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "batchId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "settlementPrice",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "buyFillRatio",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "sellFillRatio",
              type: "uint256",
            },
          ],
          name: "BatchSettled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "batchId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "enum AegisV3.BatchState",
              name: "newState",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "endBlock",
              type: "uint256",
            },
          ],
          name: "BatchStateChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "batchId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "BatchVoided",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "batchId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "filled",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "refunded",
              type: "uint256",
            },
          ],
          name: "Claimed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "batchId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "enum AegisV3.Side",
              name: "side",
              type: "uint8",
            },
          ],
          name: "Deposited",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "batchId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "enum AegisV3.Side",
              name: "side",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Disputed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "batchId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "oracleId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isValid",
              type: "bool",
            },
          ],
          name: "OraclePriceCollected",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "oracleId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "oracleAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "stackId",
              type: "uint256",
            },
          ],
          name: "OracleRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "oracleId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "oldWeight",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newWeight",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "int256",
              name: "delta1",
              type: "int256",
            },
            {
              indexed: false,
              internalType: "int256",
              name: "delta2",
              type: "int256",
            },
          ],
          name: "OracleWeightUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          inputs: [],
          name: "ACCUMULATION_DURATION",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "BASIS_POINTS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "CIRCUIT_BREAKER_THRESHOLD",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "COLLECTION_INTERVAL",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "DISPUTE_DURATION",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "DISPUTE_VOID_THRESHOLD",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "HYDRA_THRESHOLD",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_PRICE_DEVIATION",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "NEIGHBOR_DEVIATION_PCT",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "OPEN_DURATION",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "ORACLE_DEVIATION_THRESHOLD",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "PRECISION",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "PROBATION_BATCHES",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "SETTLING_DURATION",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "TRIM_PERCENT",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "WEIGHT_DEFAULT",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "WEIGHT_MAX",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "WEIGHT_MIN",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_oracleId",
              type: "uint256",
            },
          ],
          name: "activateOracle",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "batchCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "batches",
          outputs: [
            {
              internalType: "enum AegisV3.BatchState",
              name: "state",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "asset",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "openEnd",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "accumulationEnd",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "disputeEnd",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "settlingEnd",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "settlementPrice",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "buyVolume",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "sellVolume",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "buyDisputedVolume",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "sellDisputedVolume",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_batchId",
              type: "uint256",
            },
          ],
          name: "claim",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "collectOraclePrices",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "currentBatchId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_oracleId",
              type: "uint256",
            },
          ],
          name: "deactivateOracle",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
            {
              internalType: "enum AegisV3.Side",
              name: "_side",
              type: "uint8",
            },
          ],
          name: "deposit",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "dispute",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "executeSettlement",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_batchId",
              type: "uint256",
            },
          ],
          name: "getBatchState",
          outputs: [
            {
              internalType: "enum AegisV3.BatchState",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getCurrentBatchInfo",
          outputs: [
            {
              internalType: "uint256",
              name: "batchId",
              type: "uint256",
            },
            {
              internalType: "enum AegisV3.BatchState",
              name: "state",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "endBlock",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "buyVolume",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "sellVolume",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "settlementPrice",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_oracleId",
              type: "uint256",
            },
          ],
          name: "getOracleInfo",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "oracleAddress",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "weight",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "techStackId",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lastPrice",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lastUpdateBlock",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isActive",
                  type: "bool",
                },
                {
                  internalType: "uint256",
                  name: "successfulBatches",
                  type: "uint256",
                },
              ],
              internalType: "struct AegisV3.OracleInfo",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_batchId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_oracleId",
              type: "uint256",
            },
          ],
          name: "getOracleStats",
          outputs: [
            {
              internalType: "uint256",
              name: "observationCount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "trimmedAverage",
              type: "uint256",
            },
            {
              internalType: "int256",
              name: "delta1",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "delta2",
              type: "int256",
            },
            {
              internalType: "bool",
              name: "ignored",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_batchId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_user",
              type: "address",
            },
          ],
          name: "getUserOrder",
          outputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "enum AegisV3.Side",
              name: "side",
              type: "uint8",
            },
            {
              internalType: "bool",
              name: "claimed",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "disputed",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "lastCollectionBlock",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "lastSettlementPrice",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "maxStaleness",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "oracleAddressToId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "oracleCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "oracles",
          outputs: [
            {
              internalType: "address",
              name: "oracleAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "weight",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "techStackId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lastPrice",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lastUpdateBlock",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isActive",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "successfulBatches",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_oracleAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_techStackId",
              type: "uint256",
            },
          ],
          name: "registerOracle",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_asset",
              type: "address",
            },
          ],
          name: "setBatchAsset",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_seconds",
              type: "uint256",
            },
          ],
          name: "setMaxStaleness",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "startAccumulation",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "startDispute",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "startSettling",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        owner: "@openzeppelin/contracts/access/Ownable.sol",
        renounceOwnership: "@openzeppelin/contracts/access/Ownable.sol",
        transferOwnership: "@openzeppelin/contracts/access/Ownable.sol",
      },
      deployedOnBlock: 11633919,
    },
    PythOracleAdapter: {
      address: "0xDFdd46c593586028739E063204b8741bc3EF730D",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_pyth",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "_priceId",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "MAX_AGE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "latestRoundData",
          outputs: [
            {
              internalType: "uint80",
              name: "",
              type: "uint80",
            },
            {
              internalType: "int256",
              name: "",
              type: "int256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint80",
              name: "",
              type: "uint80",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "priceId",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "pyth",
          outputs: [
            {
              internalType: "contract IPyth",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 11633916,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
